### ISSUE TITLE
test lora

### ISSUE THREAD

**Issue by cardenluo** [mittimi/ComfyUI_mittimiLoadPreset2#2]
![image](https://github.com/user-attachments/assets/fea5fb8c-0346-4f73-99d1-213dbc97eff2)

Thank you for your efforts, your node has made things much more convenient for me. This version is even more user-friendly than V1.
Here are my experiences with it:
1) I'm not sure if I'm using LoRa correctly, but it seems not to be working at the moment.
2) Can the "parameters data" be directly output as a prest toml file?

**Comment by cardenluo** [comment]
sorry, I was using the wrong LoRa model. Fantastic! it runs perfectly for the lora.
![image](https://github.com/user-attachments/assets/3868bfc5-7760-468c-a928-353531216871)

**Comment by cardenluo** [comment]
![image](https://github.com/user-attachments/assets/c5305a0a-fe9f-4fbc-9292-a8b795694ae5)
Is it not possible to save this as a preset yet? Every time I perform this operation, the preset becomes invalid.

**Comment by mittimi** [comment]
@cardenluo 
OK, add a node to save parameters_data to toml. However, I will be a bit busy and will not touch the code until next week or later.

Regarding the issue of the LoRA description being invalid in the preset, I found the problem.
Including a backslash ("\") seems to cause an error.
So please use a slash when describing the path.

**Comment by cardenluo** [comment]
[ComfyUI-PromptList](https://github.com/NakamuraShippo/ComfyUI-PromptList)
![image](https://github.com/user-attachments/assets/09661ef3-b96d-4cff-96cf-cbad5ac76c19)
![image](https://github.com/user-attachments/assets/60a17b33-5744-4b5c-8292-bb12e76fa064)

The LoRA is functioning normally now, thanks to your method. I can now consolidate all processes, including XL, SD, and the accelerated version XL, into a single workflow. Thank you very much.

Additionally, your node has a great feature that allows for individual prompt word presets. There are many similar options, but none of them can be displayed in the box, including this new node  “”ComfyUI-PromptList“”. The author couldn't solve this issue when asked, but your node has actually addressed it. It allows for the selection of different presets, which are directly displayed in the box. With a bit of modification, it could become an excellent preset text node. This is because when the text is displayed in the text box, it can be directly edited a second time.

**Comment by mittimi** [comment]
@cardenluo 
Good!

I have added a node to store the presets.
I also improved the LoRA Block Weight and Negpip so that they can be used.
Please see the README for details.

**Comment by cardenluo** [comment]
Thank you, all the experiences were great.

**Comment by cardenluo** [comment]
![image](https://github.com/user-attachments/assets/5347dfcb-9820-4198-b2a2-1405d30a12a7)

Respected Sir，I’ve tried many plugins, but none of them could display the content within the content box for secondary editing; however, I’ve seen this achieved with your solution,the two loadsetparameters can be connected directly, but it looks a bit bulky. Could you specifically design a loader only for prompts?And If it supports submenu, that would be perfect.

**Comment by mittimi** [comment]
@cardenluo 
Thanks for the kind words.

Ok, Subfolders will be supported. However, I don't know if it can be made to show a list of subfolders like the image you presented. The format shown in the image below can be implemented quickly.

For the prompt-only node, is it ok if I make it on a separate page instead of here? I have a technical problem.

![111](https://github.com/user-attachments/assets/ebc6b99f-df3f-4624-820d-268daf0573b7)

**Comment by cardenluo** [comment]
Thank you, It’s already very good that it can be used.

**Comment by mittimi** [comment]
@cardenluo 
I have finished modifying the subfolder.
Perhaps the previous version has an error in the node that saves presets, etc., so please update.

I will let you know when the prompt-only node is completed.

**Comment by mittimi** [comment]
@cardenluo 
I have created a text-only node that you can use.
Please read the description on the following page.

https://github.com/mittimi/ComfyUI_mittimiLoadText
